# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 445c187e3d5cee3a18cd5b0107078e44d069c1ae7602caba85f5f8a30649d29286c7d6b29b2e110baa3fa8e12c22a941630cdf7f2ba18a7fc90e09723b21fe35

test:
  secret_key_base: 75deca15e3dad4c85b7b2077d50b6aadd3ef58d940b97932cd116809607950689c080d37046d94bedf9ab85981607d0520ef21dd2db47bc288e77958eacb5bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
